from django.urls import path

from .views import (
    create_migrations_from_vmware,
    dashboard,
    discover_now,
    health,
    list_migrations,
    migration_detail,
    openstack_endpoint_connect,
    openstack_endpoint_detail,
    openstack_endpoint_close,
    openstack_endpoint_list,
    openstack_endpoint_projects,
    openstack_endpoint_test,
    openstack_flavors,
    openstack_health,
    openstack_images,
    openstack_network_create,
    openstack_networks,
    openstack_provision_now,
    openstack_provision_status,
    openstack_router_attach_subnet,
    openstack_router_create,
    openstack_routers,
    rollback_migration_now,
    start_migration_now,
    task_status,
    vmware_endpoint_connect,
    vmware_endpoint_detail,
    vmware_endpoint_close,
    vmware_endpoint_list,
    vmware_endpoint_test,
    vmware_vms,
)

urlpatterns = [
    path("health", health, name="health"),
    path("dashboard", dashboard, name="dashboard"),
    path("openstack/health", openstack_health, name="openstack-health"),
    path("openstack/images", openstack_images, name="openstack-images"),
    path("openstack/flavors", openstack_flavors, name="openstack-flavors"),
    path("openstack/networks", openstack_networks, name="openstack-networks"),
    path("openstack/networks/create", openstack_network_create, name="openstack-networks-create"),
    path("openstack/routers", openstack_routers, name="openstack-routers"),
    path("openstack/routers/create", openstack_router_create, name="openstack-router-create"),
    path("openstack/routers/attach-subnet", openstack_router_attach_subnet, name="openstack-router-attach-subnet"),
    path("openstack/endpoints/test", openstack_endpoint_test, name="openstack-endpoints-test"),
    path("openstack/endpoints", openstack_endpoint_list, name="openstack-endpoints-list"),
    path("openstack/endpoints/connect", openstack_endpoint_connect, name="openstack-endpoints-connect"),
    path("openstack/endpoints/<int:session_id>", openstack_endpoint_detail, name="openstack-endpoints-detail"),
    path("openstack/endpoints/<int:session_id>/projects", openstack_endpoint_projects, name="openstack-endpoints-projects"),
    path("openstack/endpoints/close", openstack_endpoint_close, name="openstack-endpoints-close"),
    path("openstack/provision", openstack_provision_now, name="openstack-provision-now"),
    path("openstack/provision/status", openstack_provision_status, name="openstack-provision-status"),
    path("vmware/vms", vmware_vms, name="vmware-vms"),
    path("vmware/endpoints/test", vmware_endpoint_test, name="vmware-endpoints-test"),
    path("vmware/endpoints", vmware_endpoint_list, name="vmware-endpoints-list"),
    path("vmware/endpoints/connect", vmware_endpoint_connect, name="vmware-endpoints-connect"),
    path("vmware/endpoints/<int:session_id>", vmware_endpoint_detail, name="vmware-endpoints-detail"),
    path("vmware/endpoints/close", vmware_endpoint_close, name="vmware-endpoints-close"),
    path("vmware/discover-now", discover_now, name="vmware-discover-now"),
    path("tasks/<str:task_id>", task_status, name="task-status"),
    path("migrations", list_migrations, name="migrations-list"),
    path("migrations/<int:job_id>", migration_detail, name="migrations-detail"),
    path("migrations/from-vmware", create_migrations_from_vmware, name="migrations-from-vmware"),
    path("migrations/<int:job_id>/start", start_migration_now, name="migrations-start-now"),
    path("migrations/<int:job_id>/rollback", rollback_migration_now, name="migrations-rollback-now"),
]
