# Generated by Django 5.2.11 on 2026-02-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISCOVERED', 'Discovered'), ('CONVERTING', 'Converting'), ('UPLOADING', 'Uploading'), ('DEPLOYED', 'Deployed'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed'), ('ROLLED_BACK', 'Rolled Back')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
