# Generated by Django 5.2.11 on 2026-02-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveredVM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('workstation', 'Workstation'), ('esxi', 'ESXi')], db_index=True, max_length=20)),
                ('cpu', models.PositiveIntegerField(blank=True, null=True)),
                ('ram', models.PositiveIntegerField(blank=True, null=True)),
                ('disks', models.JSONField(blank=True, default=list)),
                ('power_state', models.CharField(blank=True, default='', max_length=64)),
                ('last_seen', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['-last_seen', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'source'), name='uq_discovered_vm_name_source')],
            },
        ),
    ]
