# Generated by Django 5.2.11 on 2026-02-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrations', '0002_discoveredvm'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationjob',
            name='conversion_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
