# Generated by Django 6.0.2 on 2026-02-17 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrations', '0005_openstack_provisioning_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenstackEndpointSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('auth_url', models.CharField(max_length=512)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=1024)),
                ('project_name', models.CharField(max_length=255)),
                ('user_domain_name', models.CharField(default='Default', max_length=255)),
                ('project_domain_name', models.CharField(default='Default', max_length=255)),
                ('region_name', models.CharField(blank=True, default='', max_length=255)),
                ('interface', models.CharField(blank=True, default='', max_length=64)),
                ('identity_api_version', models.CharField(blank=True, default='', max_length=32)),
                ('verify', models.BooleanField(default=False)),
                ('image_endpoint_override', models.CharField(blank=True, default='', max_length=512)),
                ('last_test_status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='UNKNOWN', max_length=16)),
                ('last_test_message', models.TextField(blank=True, default='')),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VmwareEndpointSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=443)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=1024)),
                ('insecure', models.BooleanField(default=True)),
                ('last_test_status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='UNKNOWN', max_length=16)),
                ('last_test_message', models.TextField(blank=True, default='')),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='discoveredvm',
            name='uq_discovered_vm_name_source',
        ),
        migrations.AddField(
            model_name='discoveredvm',
            name='vmware_endpoint_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_vms', to='migrations.vmwareendpointsession'),
        ),
        migrations.AddConstraint(
            model_name='discoveredvm',
            constraint=models.UniqueConstraint(fields=('name', 'source', 'vmware_endpoint_session'), name='uq_discovered_vm_name_source_endpoint'),
        ),
    ]
