# Generated by Django 6.0.2 on 2026-03-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrations', '0007_alter_migrationjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationjob',
            name='destination',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='migrationjob',
            name='source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
