# Generated by Django 4.2.16 on 2026-04-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrations', '0010_scope_sessions_and_encrypt_passwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmwareendpointsession',
            name='datacenter',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='discoveredvm',
            name='source',
            field=models.CharField(choices=[('workstation', 'Workstation'), ('esxi', 'ESXi'), ('vcenter', 'vCenter')], db_index=True, max_length=20),
        ),
    ]
